/**
 * Remembering swatch photos in the materials catalog.
 *
 * The swatch picker pre-fills a quote line's swatch from the chosen
 * catalog color's photo (materials[].colors[].imageId). But when a dealer
 * attaches a photo INLINE on a quote line — for a color the catalog
 * doesn't have a picture for yet — that photo only lived on the line. Next
 * quote, the same material/color came up blank again.
 *
 * This module closes the loop: when a line whose subtype was generated by
 * the picker (so it carries the canonical "MATERIAL · COLOR (#code)"
 * string) gets a swatch, we copy that image into the catalog color so the
 * next pick of that color is pre-filled. Hand-typed fabrics carry no
 * `(#code)` and never have a catalog color to remember against, so they're
 * skipped by design.
 *
 * The image is COPIED, not referenced: a quote line owns its swatch image
 * and ImageDrop deletes it when the swatch is replaced/removed, which would
 * dangle a shared catalog reference. The copy is a material-owned image.
 *
 * Fill-empty only: we never overwrite a catalog color that already has a
 * photo, so running quotes can't silently mutate an existing swatch for the
 * whole team.
 */

import { db, saveImage, downloadImageBytes } from '../db/database.js';
import { isCompoundLine } from './pricing.js';
import { colorCodeFromSubtype, locateColor } from './swatchMatch.js';

// Copy an existing image into a new material-owned image so deleting the
// source (a quote line's swatch) can never dangle the catalog reference.
async function copyImageForMaterial(imageId, materialId) {
  const src = await downloadImageBytes(imageId);
  if (!src || !src.bytes || !src.bytes.length) return null;
  const blob = new Blob([src.bytes], { type: src.contentType || 'image/png' });
  return saveImage({ kind: 'materialColor', ownerId: materialId, file: blob });
}

/**
 * Remember one line/component swatch in the catalog. No-op (returns false)
 * when the subtype carries no catalog code, no material/color matches, or
 * the color already has a photo. Best-effort: never throws.
 */
export async function rememberSwatchInCatalog({ profileId, subtype, imageId }) {
  try {
    if (!profileId || !imageId || !subtype) return false;
    if (!colorCodeFromSubtype(subtype)) return false;
    const materials = await db.materials.where('profileId').equals(profileId).toArray();
    const hit = locateColor(materials, subtype);
    if (!hit) return false;
    if (hit.material.colors[hit.idx].imageId) return false; // fill-empty only
    const copyId = await copyImageForMaterial(imageId, hit.material.id);
    if (!copyId) return false;
    const colors = hit.material.colors.map((c, i) => (i === hit.idx ? { ...c, imageId: copyId } : c));
    await db.materials.update(hit.material.id, { colors, updatedAt: Date.now() });
    return true;
  } catch (err) {
    console.error('[swatchCatalog] rememberSwatchInCatalog failed:', err);
    return false;
  }
}

// Every (subtype, imageId) swatch source on a line: the line itself plus
// each compound component that carries its own swatch.
function swatchSourcesOf(line) {
  const out = [];
  if (line.swatchImageId) out.push({ subtype: line.subtype, imageId: line.swatchImageId });
  if (isCompoundLine(line)) {
    for (const c of line.components || []) {
      if (c.swatchImageId) out.push({ subtype: c.subtype, imageId: c.swatchImageId });
    }
  }
  return out;
}

/**
 * One-shot backfill: scan every quote line + component and copy any swatch
 * whose subtype maps to an empty catalog color into that color. Idempotent
 * (fill-empty), safe to re-run. Returns { scanned, matched, filled }.
 */
export async function backfillSwatchesFromQuotes(profileId) {
  const result = { scanned: 0, matched: 0, filled: 0 };
  if (!profileId) return result;

  const materials = await db.materials.where('profileId').equals(profileId).toArray();
  // Work on cloned color arrays so we batch one DB write per changed
  // material and so fills made earlier in this run are seen by later lines.
  const working = new Map(); // materialId → cloned colors[]
  const dirty = new Set();
  const colorsOf = (material) => {
    if (!working.has(material.id)) {
      working.set(material.id, (material.colors || []).map((c) => ({ ...c })));
    }
    return working.get(material.id);
  };

  const lines = await db.quoteLines.toArray();
  for (const line of lines) {
    for (const src of swatchSourcesOf(line)) {
      result.scanned++;
      const hit = locateColor(materials, src.subtype);
      if (!hit) continue;
      result.matched++;
      const colors = colorsOf(hit.material);
      if (colors[hit.idx].imageId) continue; // already filled (catalog or earlier this run)
      const copyId = await copyImageForMaterial(src.imageId, hit.material.id);
      if (!copyId) continue;
      colors[hit.idx] = { ...colors[hit.idx], imageId: copyId };
      dirty.add(hit.material.id);
      result.filled++;
    }
  }

  for (const materialId of dirty) {
    await db.materials.update(materialId, { colors: working.get(materialId), updatedAt: Date.now() });
  }
  return result;
}
