/**
 * dwg2plan — turn Ligne Roset Togo CAD blocks into the configurator's web assets.
 *
 * Input : scripts/togo-dwg/togo_<id>.dwg  (AutoCAD 2013 blocks; cm; INSUNITS=5)
 * Output: src/assets/togo/togo_<id>.svg   (clean top-down plan symbol)
 *         src/assets/togo/pieces.js        (pure metadata: footprint + labels)
 *
 * HOW IT WORKS (and why it's safe to re-run):
 *   The model space holds only INSERTs; the real geometry lives in BLOCK_RECORDs,
 *   organised onto layers. Ligne Roset authored a dedicated "Mobilier 2D" layer —
 *   the architect's top-down plan symbol — so we resolve INSERT→block recursively,
 *   apply each insert's affine transform, keep ONLY that layer, and project to XY.
 *   Output is normalised: viewBox = the real cm footprint, stroke = currentColor
 *   (so the app themes it), all strokes merged into ONE <path> to keep the file
 *   small. The libredwg WASM parser is a BUILD-TIME tool only — it never ships to
 *   the browser; the committed .svg + pieces.js are what the app imports.
 *
 * Run:  node scripts/dwg2plan.mjs      (needs the @mlightcad/libredwg-web devDep)
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LibreDwg, Dwg_File_Type } from '@mlightcad/libredwg-web';
// The geometry (block resolution, plan-layer filter, SVG emit) is the SAME pure
// module the in-browser uploader uses — so a seeded asset and a dealer-uploaded
// one are produced identically.
import { planFromDb } from '../src/lib/togo/planGeometry.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const IN_DIR = join(HERE, 'togo-dwg');
const OUT_DIR = join(ROOT, 'src', 'assets', 'togo');
const WASM = join(ROOT, 'node_modules', '@mlightcad', 'libredwg-web', 'wasm/');

// Per-piece presentation + matching metadata (footprint cm is MEASURED, not set
// here). Keyed by the DWG file stem. `match` keywords let the app auto-bind a
// piece to a Togo model in the live catalog (any language the dealer named it).
const META = {
  togo_a:      { id: 'a',      label: 'Sillón Togo',        model: 'armchair',     order: 2, match: ['togo', 'fauteuil', 'armchair', 'sillon', 'butaca'] },
  togo_chauf:  { id: 'chauf',  label: 'Chofesa Togo',       model: 'fireside',     order: 1, match: ['togo', 'chauffeuse', 'fireside', 'chofesa', 'sin brazos'] },
  togo_gb:     { id: 'gb',     label: 'Sofá Togo',          model: 'settee',       order: 3, match: ['togo', 'settee', 'sofa', 'canape', 'canapé', '2'] },
  togo_mc:     { id: 'mc',     label: 'Sofá grande Togo',   model: 'large-settee', order: 4, match: ['togo', 'grand', 'large', 'grande', '3'] },
  togo_lounge: { id: 'lounge', label: 'Meridiana Togo',     model: 'lounge',       order: 5, match: ['togo', 'lounge', 'meridienne', 'chaise', 'meridiana', 'angle', 'corner'] },
};

const libredwg = await LibreDwg.create(WASM);
const files = readdirSync(IN_DIR).filter((f) => f.endsWith('.dwg'));
const pieces = [];

for (const file of files) {
  const stem = file.replace(/\.dwg$/, '');
  const meta = META[stem];
  if (!meta) { console.warn('skip (no metadata):', file); continue; }

  const dwg = libredwg.dwg_read_data(new Uint8Array(readFileSync(join(IN_DIR, file))), Dwg_File_Type.DWG);
  const db = libredwg.convert(dwg);
  const { svg, widthCm, depthCm, polyCount } = planFromDb(db); // defaults to the "Mobilier 2D" plan layer
  libredwg.dwg_free(dwg);

  writeFileSync(join(OUT_DIR, `${stem}.svg`), `${svg}\n`);
  pieces.push({ ...meta, widthCm, depthCm, svgFile: `${stem}.svg`, paths: polyCount });
  console.log(`${stem}: ${widthCm}×${depthCm} cm · ${polyCount} polylines · ${((svg.length + 1) / 1024).toFixed(1)} KB`);
}

// Stable order for the palette.
pieces.sort((a, b) => a.order - b.order);
const body = pieces.map((p) =>
  `  { id: ${JSON.stringify(p.id)}, label: ${JSON.stringify(p.label)}, model: ${JSON.stringify(p.model)}, `
  + `widthCm: ${p.widthCm}, depthCm: ${p.depthCm}, svgFile: ${JSON.stringify(p.svgFile)}, match: ${JSON.stringify(p.match)} },`
).join('\n');
const piecesJs =
  `// GENERATED by scripts/dwg2plan.mjs from the Ligne Roset Togo CAD blocks — do not edit by hand.\n`
  + `// Footprints are MEASURED from each DWG's "Mobilier 2D" plan layer (centimetres).\n`
  + `// Pure metadata (no asset imports) so the ViewModel + tests can read it in Node.\n`
  + `export const TOGO_PIECES = [\n${body}\n];\n`;
writeFileSync(join(OUT_DIR, 'pieces.js'), piecesJs);
console.log(`\nWrote ${pieces.length} pieces → src/assets/togo/{*.svg,pieces.js}`);
